
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.HBox hbox1;
	private global::Gtk.HButtonBox hbuttonbox4;
	private global::Gtk.Button button139;
	private global::Gtk.Button button140;
	private global::Gtk.Button button141;
	private global::Gtk.Entry entry1;
	private global::Gtk.Statusbar statusbar1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hbuttonbox4 = new global::Gtk.HButtonBox ();
		this.hbuttonbox4.Name = "hbuttonbox4";
		this.hbuttonbox4.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
		// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
		this.button139 = new global::Gtk.Button ();
		this.button139.CanFocus = true;
		this.button139.Name = "button139";
		this.button139.UseUnderline = true;
		this.button139.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox4.Add (this.button139);
		global::Gtk.ButtonBox.ButtonBoxChild w1 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4 [this.button139]));
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
		this.button140 = new global::Gtk.Button ();
		this.button140.CanFocus = true;
		this.button140.Name = "button140";
		this.button140.UseUnderline = true;
		this.button140.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox4.Add (this.button140);
		global::Gtk.ButtonBox.ButtonBoxChild w2 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4 [this.button140]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
		this.button141 = new global::Gtk.Button ();
		this.button141.CanFocus = true;
		this.button141.Name = "button141";
		this.button141.UseUnderline = true;
		this.button141.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox4.Add (this.button141);
		global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4 [this.button141]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		this.hbox1.Add (this.hbuttonbox4);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hbuttonbox4]));
		w4.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.entry1 = new global::Gtk.Entry ();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '●';
		this.hbox1.Add (this.entry1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.entry1]));
		w5.Position = 2;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		this.vbox1.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 953;
		this.DefaultHeight = 498;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
